#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod 'camptocamp-kmod', '2.5.0'
mod 'camptocamp-systemd', '2.10.0'
mod 'cmdntrf-consul_template', '2.3.3'
mod 'derdanne-nfs', '2.1.6'
mod 'heini-wait_for', '2.2.0'
mod 'herculesteam-augeasproviders_core', '2.6.0'
mod 'herculesteam-augeasproviders_pam', '2.2.1'
mod 'herculesteam-augeasproviders_shellvar', '4.0.0'
mod 'herculesteam-augeasproviders_ssh', '4.0.0'
mod 'herculesteam-augeasproviders_sysctl', '2.5.1'
mod 'petems-swap_file', '4.0.2'
mod 'puppet-archive', '4.6.0'
mod 'puppet-epel', '3.0.1'
mod 'puppet-fail2ban', '4.2.0'
mod 'puppet-healthcheck', '1.0.1'
mod 'puppet-logrotate', '5.0.0'
mod 'puppet-nodejs', '8.1.0'
mod 'puppet-prometheus', '12.5.0'
mod 'puppet-selinux', '3.2.0'
mod 'puppet-squid', '3.0.0'
mod 'puppet-staging', '3.2.0'
mod 'puppet-yum', '4.3.0'
mod 'puppetlabs-concat', '6.2.0'
mod 'puppetlabs-firewall', '2.7.0'
mod 'puppetlabs-inifile', '4.3.1'
mod 'puppetlabs-lvm', '1.4.0'
mod 'puppetlabs-mount_core', '1.0.4'
mod 'puppetlabs-mysql', '12.0.1'
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-transition', '0.1.3'
mod 'yelp-netstdlib', '0.0.1'
mod 'KyleAnderson-consul', '6.1.0'
mod 'treydock-globus', '6.0.1'

mod 'computecanada-jupyterhub',
    :git => 'https://github.com/ComputeCanada/puppet-jupyterhub.git',
    :ref => 'v4.8.1'
