#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod 'cmdntrf-consul_template', '2.3.6'
mod 'derdanne-nfs', '2.1.11'
mod 'heini-wait_for', '2.2.0'
mod 'puppet-augeasproviders_core', '4.0.1'
mod 'puppet-augeasproviders_pam', '4.0.0'
mod 'puppet-augeasproviders_shellvar', '6.0.0'
mod 'puppet-augeasproviders_ssh', '6.0.0'
mod 'puppet-augeasproviders_sysctl', '3.1.0'
mod 'petems-swap_file', '4.0.2'
mod 'puppet-archive', '4.6.0'
mod 'puppet-consul', '7.3.1'
mod 'puppet-epel', '5.0.0'
mod 'puppet-extlib', '7.0.0'
mod 'puppet-fail2ban', '4.2.0'
mod 'puppet-healthcheck', '1.0.1'
mod 'puppet-kmod', '4.0.0'
mod 'puppet-logrotate', '5.0.0'
mod 'puppet-prometheus', '12.5.0'
mod 'puppet-selinux', '3.4.1'
mod 'puppet-squid', '3.0.0'
mod 'puppet-systemd', '3.10.0'
mod 'puppet-yum', '6.2.0'
mod 'puppetlabs-concat', '7.4.0'
mod 'puppetlabs-firewall', '5.0.0'
mod 'puppetlabs-inifile', '6.1.0'
mod 'puppetlabs-lvm', '1.4.0'
mod 'puppetlabs-motd', '7.1.0'
mod 'puppetlabs-mount_core', '1.0.4'
mod 'puppetlabs-mysql', '13.3.0'
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-transition', '0.1.3'
mod 'treydock-globus', '9.0.0'

mod 'computecanada-jupyterhub',
    :git => 'https://github.com/ComputeCanada/puppet-jupyterhub.git',
    :ref => 'v5.0.1'
