#!/usr/bin/env bash
export PATH=/opt/puppetlabs/bin:$PATH
set -euo pipefail

echo "Checking Puppet .pp files for syntax errors..."
for file in $(find $(find . -name manifests -type d) -type f -name "*.pp"); do
    echo $file
    puppet parser validate --debug $file
done

echo "Checking Puppet .epp files for syntax errors..."
for file in $(find $(find . -name templates -type d) -type f -name "*.epp"); do
    echo $file
    puppet epp validate --debug $file
done
