#!/usr/bin/env bash
set -euo pipefail

puppet-lint manifests/* site/profile/manifests/* \
--no-autoloader_layout-check \
--fail-on-warnings \
--no-arrow_alignment-check \
--no-single_quote_string_with_variables-check \
--no-140chars-check \
--no-documentation-check \

