name: Test complete puppet environment

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Install incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x
      - name: Reset the firewall
        run: |
          sudo nft flush ruleset
      - name: Init incus
        run: |
          sudo incus admin init --auto
          sudo adduser $USER incus-admin
          newgrp incus-admin
      - name: Download Magic Castle Incus
        run: |
          curl -L -O https://raw.githubusercontent.com/ComputeCanada/magic_castle/refs/heads/main/examples/incus/main.tf
          curl -L -O https://raw.githubusercontent.com/ComputeCanada/magic_castle/refs/heads/main/examples/incus/data.yaml
      - name: Init and apply
        run: |
          sed -i "s;\"main\";\"${GITHUB_REF}\";" main.tf
          terraform init
          terraform apply -auto-approve