name: Test complete puppet environment

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Install incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x
      - name: Reset the firewall
        run: |
          sudo nft flush ruleset
      - name: Init incus
        run: |
          sudo incus admin init --auto
      - name: Download Magic Castle Incus
        run: |
          curl -L -O https://raw.githubusercontent.com/ComputeCanada/magic_castle/refs/heads/main/examples/incus/main.tf
          curl -L -O https://raw.githubusercontent.com/ComputeCanada/magic_castle/refs/heads/main/examples/incus/data.yaml
      - name: Init and apply
        run: |
          sed -i "s;\"main\";\"${GITHUB_REF}\";" main.tf
          sudo chgrp runner /var/lib/incus/unix.socket
          terraform init
          terraform apply -auto-approve
      - name: Wait for puppet catalog to be applied
        timeout-minutes: 15
        run: |
          incus project switch $(incus project list -c n --format csv | grep -v 'default' | cut -f1 -d' ')
          for nodename in $(incus list -c n -f csv); do
            PUPPET_APPLIED=1
            echo -n $nodename
            until [ $PUPPET_APPLIED -eq 0 ]; do
              incus exec $nodename -- journalctl -u puppet | grep "Applied catalog"
              PUPPET_APPLIED=$?
              echo -n .
              sleep 10
            done
            echo
          done
      - name: Verify Puppet catalog for errors
        run: |
          SUCCESSFUL=0
          incus project switch $(incus project list -c n --format csv | grep -v 'default' | cut -f1 -d' ')
          for nodename in $(incus list -c n -f csv); do
            incus exec $nodename -- journalctl -u puppet | grep "failed dependencies"
            if $?; then
              echo "### ${nodename}" >> $GITHUB_STEP_SUMMARY
              echo "```"
              incus exec $nodename -- journalctl -u puppet >> $GITHUB_STEP_SUMMARY
              echo "```"
              SUCCESSFUL=1
            fi
          done
          exit $SUCCESSFUL
